#!/usr/bin/env node

import * as http from 'http';
import * as proc from 'process';

function ping(name) {
    let start = Date.now();
    let req = http.get('http://' + name, (res) => {
        res.on('end', (err) => {
            proc.stderr.write(JSON.stringify(err) + '\t' + ((Date.now() - start) / 1000) + '\n');
            setTimeout(()=>ping(name), 1000);
        });
        proc.stderr.write(JSON.stringify(res.statusCode) + '\t' + ((Date.now() - start) / 1000) + '\n');
        setTimeout(()=>ping(name), 1000);
    })
}

if (proc.argv.length < 3) {
    proc.stderr.write("Usage: " + proc.argv[1] + " <destination.you.want>\n")
} else {
    ping(proc.argv[2]);
}